// Contributions Report: a working report by Shaikha Alkhaldi on how each member's material was used in the draft handbook.
module.exports = [

['h1', '1. About this report'],
['ul', [
  'This working report explains how each team member’s material was used in the draft handbook: what was taken, what was edited, what was left out, and why. Section 7 lists the work done on the handbook itself, under the name of Shaikha Alkhaldi.',
  'The handbook it describes is a **draft for the team’s review**, not the final version. Every decision below can be discussed and changed.',
  'The report follows the current draft: two editions (Midnight and Light) with the same content, 98 pages, 9 parts and 27 chapters, an opening section (**Start here**) and a closing section (**Your journey continues**).',
  'Members are listed in alphabetical order. Chapter numbers refer to the current draft.',
  'Every item of every document is listed, with its place in the handbook and the reason it was or was not used, in the separate **Appendix: Item-by-item record of the team’s material**.',
]],

['h1', '2. How material was chosen'],
['p', 'Every point was judged by two questions: does a beginner need it, and is it correct? This led to six working rules:'],
['ol', [
  'Each idea is explained with an example before it is named, in numbered steps.',
  'Each topic appears once, in the chapter where it belongs, even when several members covered it. As the framework agreed, material that appeared in several members’ notes was kept first, and material from one member was reviewed case by case.',
  'Anything that could not be checked was left out rather than printed.',
  'Examples that took a political or religious position were rewritten or left out.',
  'History and specialist theory were kept to a minimum; they are available in other books.',
  'Every idea taken from a published work is cited in brackets, and listed in the References.',
]],

['h1', '3. Where each chapter comes from'],
['p', 'The table shows the main source of each part of the draft, and what else was added to it.'],
['table', ['Section', 'Main source', 'Also added'], [
  ['Start here', 'Written by Shaikha Alkhaldi', 'The news-report example (_came under pressure_); the House of Wisdom; the four steps'],
  ['1 Translation and the translator', 'Samiuallah Mohammad (draft)', 'Shaikha’s notes: three kinds of translation, the translator as a reader; the Rosetta Stone'],
  ['2 Tips, advice and preparation', 'Masooma Almesri (idea); Samiuallah (draft tips and plan)', 'Shaikha’s framework: the three questions (client, purpose, audience); a worked first translation'],
  ['3 Printed and digital dictionaries', 'Loulwah Bin Saeed (idea); Samiuallah (plan)', 'Written by Shaikha Alkhaldi from published sources; {{كتاب العين}}'],
  ['4 English and Arabic: key differences', 'Samiuallah (draft; 180, Translation 1 and Farghal & Shunnaq notes)', 'Shaikha’s notes: _be_, _do_, _have_, the dual, gender of _I_ and _you_; Arabic numerals'],
  ['5 Form and meaning', 'Samiuallah (draft)', '—'],
  ['6 Types of meaning', 'Samiuallah (draft)', 'Shaikha’s notes: lexical gaps, false equivalents, rare words'],
  ['7 Context', 'Samiuallah (draft)', 'Shaikha’s notes: {{خط}}; the verb _run_'],
  ['8 Collocation', 'Samiuallah (draft)', 'Shaikha’s notes: _deliver_; Farghal & Shunnaq notes: _weak coffee_, _a rough sea_, the collocations of {{يقطع}}'],
  ['9 Idioms, proverbs and fixed expressions', 'Samiuallah (draft)', 'Shaikha’s notes: fixed expressions, spotting idioms, five ways to translate them; 180 notes and {{الترجمة: ماهيتها وكيفيتها}}: three idioms; Kuwaiti expressions from the Kuwaiti dictionary (Loulwah’s proposal)'],
  ['10 Equivalence', 'Samiuallah (draft)', 'Citation of Farghal & Shunnaq'],
  ['11 Literal and free translation', 'Samiuallah (draft)', 'Communicative translation (requested in the Teams chat)'],
  ['12 Metaphoric translation', 'Samiuallah (draft)', 'Masooma’s slides: {{عقارب الساعة}}, _a throbbing headache_'],
  ['13 The seven translation procedures', 'Samiuallah (plan); written by Shaikha Alkhaldi from published sources', 'Examples from Samiuallah’s Farghal & Shunnaq notes and draft: _shadow government_, _My friend speaks German fluently_, _A burnt child dreads the fire_, _garage_'],
  ['14 Translation strategies', 'Samiuallah (draft and Translation 1 notes)', 'Explicitation and implicitation (Teams chat); further strategies; Shaikha’s notes: Arabic words in English'],
  ['15 Cultural approximation', 'Samiuallah (draft)', 'Citation of Farghal & Shunnaq'],
  ['16 Descriptive translation', 'Samiuallah (draft)', 'Citation of Farghal & Shunnaq'],
  ['17 Lexical creation', 'Samiuallah (draft)', 'Shaikha’s notes: Arabicisation examples; Masooma’s slides: {{الاستمطار}}, {{قطار}}, affixes; the journey of _coffee_'],
  ['18 Text analysis', 'Samiuallah (draft and Text Analysis Model)', '—'],
  ['19 Text types and genres', 'Samiuallah (plan); Shaikha (framework)', 'Shaikha’s notes: news headlines, the inverted pyramid, technical and literary texts'],
  ['20 Words and points of view', 'Samiuallah (plan: the relational model; draft: the _suicide bomber_ example)', 'Written by Shaikha Alkhaldi from published sources'],
  ['21 Terminology', 'Masooma and Samiuallah (terminology material from Masooma’s slides)', 'Shaikha’s terminology class notes: the research steps; Shaikha’s notes: medical examples; UNTERM, Arabterm, a sample term list; the Damascus academy'],
  ['22 Machine translation', 'Samiuallah (draft: post-editing; plan); Loulwah (framework: a practical guide to digital tools)', 'Shaikha’s notes: translation memory, CAT tools, localisation; the 1954 demonstration'],
  ['23 Revision and common mistakes', 'Masooma (idea); Samiuallah (plan); Shaikha (framework)', 'Written by Shaikha Alkhaldi from published sources'],
  ['24 Interlingual risk assessment', 'Shaikha (framework)', 'The _Mars Climate Orbiter_'],
  ['25 Translation commentary', 'Samiuallah (draft and Text Analysis Model)', '—'],
  ['26 Introduction to audiovisual translation', 'Loulwah (AVT notes)', 'Shaikha’s notes: the Arabic dubbing of _The Simpsons_; the AVT notes: silent-film intertitles (a Did you know? box)'],
  ['27 Subtitling', 'Loulwah (AVT notes)', 'Subtitle timing, SDH, a five-step method, rules for Arabic subtitles'],
  ['Your journey continues', 'Written by Shaikha Alkhaldi', '—'],
], [30, 32, 38]],

// ================= LOULWAH =================
['h1', '4. Loulwah Bin Saeed'],
['p', 'Material received: the audiovisual translation notes (Intro to AVT and AVT 2), idiom notes, and her suggestion to include dictionaries. Her Principles of Translation notes, the Gamal article and the AVT Theory file have not yet been received, and her other notes were lost.'],
['p', 'A typed and organised version of the same notes (Audiovisual Translation.docx), posted by Samiuallah Mohammad, was compared with Chapters 26 and 27. It contains no new material: everything suitable for beginners was already in the handbook, and the parts left out are the same as below. It still gives the old line length (32 to 41 characters), which the handbook corrects. The parts left out would suit the website, as Samiuallah Mohammad suggested.'],
['h2', '4.1 What was received'],
['ul', ['An introduction to audiovisual translation (AVT): why it is special, its earlier names and its types, with four video links.', 'Typed notes on AVT: types, theories, challenges, the Arab context, dubbing, subtitling, taboo language and censorship.', 'Idiom notes: 18 English idioms, most with a Kuwaiti equivalent.', 'Proposals for the framework: digital tools, machine translation, Kuwaiti expressions, and examples.', 'Suggestions on dictionaries that helped the team.']],
['h2', '4.2 What was taken, and where'],
['table', ['What', 'Where in the handbook'], [
['AVT as one field and the term used throughout; {{الترجمة السمعية البصرية}}; AVT depends on technology; images, sound and written words work together (Gambier, 2003)', 'Chapter 26, Step 1; Words to remember'],
['The four main types: subtitling, dubbing, voice-over ({{التعليق الصوتي}}), audio description ({{الوصف الصوتي}}); the documentary example', 'Chapter 26, Step 2; Words to remember; Try it'],
['Dubbing in cartoons, games and commercials; its challenges: lip movements, cultural content, consistency across a series', 'Chapter 26, Step 2'],
['Skopos theory: the purpose of a translation decides how it is translated; {{نظرية الغاية}}; the client and the target audience', 'Chapter 26, Steps 3 and 5; Chapter 2'],
['The four challenges: culture, language, technology, creativity; hard items (jokes, wordplay, songs, slang)', 'Chapter 26, Step 4'],
['Subtitling defined (dialogue, on-screen text, song lyrics); {{السترجة}}; two lines, about 37 to 39 characters', 'Chapter 27, Step 1; Words to remember; Remember'],
['Kinds of subtitles: intralingual and interlingual, offline and live, open and closed', 'Chapter 27, Step 1; Try it'],
['Speech cut to short written lines; subtitle must match the screen', 'Chapter 27, Steps 2 and 3'],
['Dialogue lists ({{قائمة الحوار}})', 'Chapter 27, Step 2; Chapter 26, Step 5'],
['How characters speak: sociolect, idiolect, slang', 'Chapter 27, Step 3'],
['Culture-bound terms ({{مصطلح ذو خصوصية ثقافية}}); sources of cultural references (Díaz Cintas and Remael, 2007)', 'Chapter 27, Step 4; Words to remember'],
['Eight strategies for cultural references, from Pedersen (2011) and Díaz Cintas and Remael (2007)', 'Chapter 27, Step 4; Try it'],
['Taboo language ({{اللغة المحظورة}}); censorship ({{الرقابة}}) and self-censorship', 'Chapter 27, Step 5; Words to remember'],
['Six Kuwaiti expressions from her Kuwaiti dictionary, such as {{الحجي سهل}} and {{العين أوسع من الدار}}', 'Chapter 9, Step 5; Chapter 15, Step 1; Chapter 27, Step 3'],
['Her proposal for a section on digital tools and machine translation: when a machine helps, typical mistakes, post-editing, safety rules', 'Chapter 22, Steps 2 to 6; the one-page guide'],
['Digital resources and dictionaries (UNTERM, Arabterm; translation memory and CAT tools)', 'Chapter 3, Steps 1 to 3; Chapter 21, Step 3; Chapter 22, Step 1'],
['Examples of how context changes a translation (bank, case, {{عين}}, a piece of cake)', 'Chapter 7, Step 3; Chapter 9, Step 2'],
['Examples of common mistakes, as weak-then-better pairs', 'Chapter 23, Steps 2 and 3']
], [58, 42]],
['h2', '4.3 What was edited or corrected'],
['ul', ['**Subtitle length.** The notes give 32 to 41 characters per line. The handbook says about 37 to 39 (up to 42 on some platforms) and tells learners to follow the client’s style guide.', '**Arabic term.** The gloss for voice-over was changed to {{التعليق الصوتي}}.', '**Absolute claims softened.** “The only type of translation that relies entirely on technology” became “depends heavily on technology”. “Only” was also dropped for the mix of image, sound and text, and for the change from speech to writing. “The fastest-growing strand” became “one of the fastest-growing areas”, and the fifteen-year span was removed because it goes out of date.', '**Two lists merged.** The two lists of strategies for cultural references became one list of eight, with both names shown, for example “Loan (retention)” and “Calque (direct translation)”.', '**Jargon made plain.** Verbal and non-verbal signs, anchoring, redundancy and marked speech became everyday words and short tips. The definition of slang as “a type of jargon” was not carried over.', '**Skopos theory shortened** to one idea and credited to Reiss and Vermeer (1984).', '**Kuwaiti expressions.** Six were chosen and cited to the dictionary; a Modern Standard Arabic version was added for {{الحجي سهل}}.', '**Proposals widened.** The digital tools section became Chapter 22 and now also covers translation memory and CAT tools.']],
['h2', '4.4 What was not taken, and why'],
['table', ['Not taken', 'Why'], [
['Growth of AVT research (courses, conferences); needs created by technology; early research interest; the earlier names (film, screen and multimedia translation, language transfer); the debate on translation versus adaptation; semiotic cohesion and the term semiotics', 'Too theoretical or historical for beginners. The handbook uses only “audiovisual translation”.'],
['Descriptive Translation Studies, Reception Studies, Polysystem Theory; the link between Skopos and dynamic equivalence', 'Too advanced; the AVT chapters keep only Skopos theory.'],
['Free commentary, in-vision signing, audio subtitling, partial dubbing, fandubbing, bilingual and multilingual subtitles, surtitles, fansubs, interpreting', 'Specialised types. The handbook introduces only four main types.'],
['The Arab-world discussion: policy, the young population, missed opportunities, advice for universities', 'Beyond a beginner’s handbook; the notes name no source for it.'],
['Humour, irony, sarcasm, religious texts, political speeches; transposition, lexical recreation and addition; the medium-shot detail for lip-sync', 'Left out for space. The strategy list is kept to eight, and coining new words is taught in Chapter 17.'],
['Four video links', 'The links were not checked.'],
['Idioms with no Arabic or Kuwaiti equivalent (for example, nosy parker, near and dear to my heart, mister perfect); an unfinished entry; idioms whose English needed correcting (cup runneth over, rear-view mirror, just deserts)', 'Incomplete or unclear entries.'],
['Twelve colloquial equivalents', 'Dialect equivalents. The handbook keeps only six Kuwaiti expressions from the dictionary.'],
['Denotation and connotation; the foreign-to-target culture point; the empty References heading; the table of phrases with Kuwaiti equivalents', 'Taught elsewhere (Chapters 4 and 6), replaced by the handbook’s own References list, or never made.'],
['Notes compiled from Baker and Munday; the article “AVT in the Arab World”; the “AVT Theory” file; the rest of her notes; dictionary examples and machine translation material', 'Not received.']
], [55, 45]],
['h2', '4.5 Added by Shaikha Alkhaldi to her chapters'],
['p', 'Subtitle display time and spotting, subtitles for the deaf and hard of hearing (SDH), a five-step subtitling method, a worked example of shortening a line, rules for Arabic subtitles, first steps for beginners, and full reference entries for the published sources her notes already named (Díaz Cintas & Remael; Pedersen; Pérez-González; Gambier; Reiss & Vermeer).'],

// ================= MASOOMA =================
['h1', '5. Masooma Almesri'],
['p', 'Material received: the terminology slides (182), the terminology material selected from them with Samiuallah Mohammad, the TerminologyIdioms document, and her framework proposals: an opening chapter of tips, a glossary, a separate chapter on idioms, and a chapter on common mistakes. Her Translation Texts document (180 and 386 texts) and her stylistics summary have not yet been received.'],
['h2', '5.1 What was received'],
['ul', ['The terminology slides (182 slides): the full course on terminology, from its history and schools to termbases, standards and Arabic term-formation.', 'A terminology chapter selected from those slides with Samiuallah Mohammad.', 'The TerminologyIdioms document: the slide outline plus a list of about 60 English idioms.', 'Her framework proposals: a glossary, an opening chapter of tips, a separate idioms chapter, and a chapter on common mistakes.', 'Not received: the Translation Texts document (texts from the 180 and 386 courses) and the stylistics summary.']],
['h2', '5.2 What was taken, and where'],
['table', ['What was taken', 'Where in the handbook'], [
  ['A one-line definition of _terminology_ (with a citation to Cabré, 1999) and of _terminologist_ and _termbase_', 'Words to remember, Chapter 21; Chapter 21, Step 1'],
  ['The four short forms: initialisms (CBC), acronyms (LASER), abbreviations (vol.), clippings (super)', 'Chapter 21, Step 1; LASER in Try it question 2'],
  ['Translators use glossaries, dictionaries and termbases; a terminologist works on the terms of a field', 'Chapter 21, Step 2; Try it question 1'],
  ['The Arabic academies that approve terms (Cairo, Baghdad, Amman)', 'Chapter 21, Step 2 and Step 3 (third point)'],
  ['How to translate a term: study its meaning, its origin, then find an equivalent that matches the concept', 'Chapter 21, Step 3 (first three points)'],
  ['When no dictionary helps, think like a terminologist: create an accurate term and record it', 'Chapter 21, Step 3 (fourth point); Try it question 3'],
  ['Rules for good terms: clear, short, one meaning, no repeating; the example {{التطرّف الراديكالي}}', 'Chapter 21, Step 3 (fourth point)'],
  ['Do not change an accepted term without a good reason', 'Chapter 21, Step 5 (second paragraph)'],
  ['Technical dictionaries, renamed _specialised dictionary_', 'Chapter 21, Step 4; Chapter 3'],
  ['Termbases: what they are and what an entry holds (term in each language, definition, field, source, date)', 'Chapter 21, Step 4'],
  ['Why terms must be managed: several names for one idea confuse readers and stop reuse', 'Chapter 21, Step 5'],
  ['Skills of the translator (from the skills slides and notes)', 'Chapter 1, Step 4'],
  ['Affix examples: _manageable_ ({{قابل للإدارة}}), _antibiotic_ ({{مضاد حيوي}})', 'Chapter 17, Step 2'],
  ['Derivation and metaphor in coining terms: {{الاستمطار}} from {{مطر}} (cloud seeding); {{قطار}} once a line of camels', 'Chapter 17, Step 2 (first method)'],
  ['Metaphor across languages: {{عقارب الساعة}}; _a throbbing headache_ ({{صداع نابض}})', 'Chapter 12, Step 3'],
  ['Idioms: _raining cats and dogs_, _spill the beans_ ({{أفشى السرّ}})', 'Chapter 9, Steps 1 and 3; Chapter 2; Chapter 14, Step 1; Chapter 22, Step 3'],
  ['_Kick the bucket_, as an informal way to say _die_', 'Chapter 6, Step 1'],
  ['Her proposal of a glossary of key terms', 'Glossary at the back; Words to remember in every chapter'],
  ['Her proposal of an opening chapter of tips and preparation', 'Chapter 2'],
  ['Her proposal of idioms as a separate chapter, widened to proverbs, fixed expressions and Kuwaiti expressions', 'Chapter 9'],
  ['Her proposal of a chapter on common mistakes, combined with revision', 'Chapter 23'],
], [62, 38]],
['h2', '5.3 What was edited or corrected'],
['ul', ['A terminologist was described as working in one language while a translator works in two. This was corrected: a terminologist works in one or more languages, and the real contrast is whole texts versus the terms of a field.', 'Initialisms and acronyms are now defined by how the letters are read (one by one, or as a word), not by what they stand for. Only one example of each short form was kept where the slides gave several.', 'The ten-step method of the Egyptian academy and the methods of the Iraqi and Jordanian academies were cut to one sentence naming the academies. Damascus and the Rabat bureau were added.', 'The rules for naming terms were reduced to one sentence, and the advice on translating a term was extended with the client’s guide, UNTERM and Arabterm, plus two steps on creating and recording a term.', 'Termbase benefits were cut to “A team can share and update it”, and the terminology background was cut to the definition alone.', 'Arabic examples were corrected or respelt: {{عقرب الساعة}} became {{عقارب الساعة}}, and the affix examples were spelt _manageable_ and _antibiotic_, with _greenish_ added.', 'Three idioms from her list (raining cats and dogs, spill the beans, kick the bucket) also appear in other notes, so they were merged into one treatment, and Arabic equivalents were added where her list had none.', 'Her opening chapter of tips was placed as Chapter 2, after the introduction, and written as steps before, during and after translating.']],
['h2', '5.4 What was not taken, and why'],
['table', ['Not taken', 'Why'], [
  ['The origins of terminology; Wüster and the Vienna, Prague and Moscow schools; the four periods, 1930 to today; the first standardisation committee (1936)', 'History is not needed to use terms well.'],
  ['Three approaches of the classical schools; four points of view on terminology; working orientations; characteristics of the field; terminography; categories of terms by function and by meaning', 'Theory beyond a beginner’s level, or too theoretical.'],
  ['ISO, ITU and IEC; how standards are voted on; de jure and de facto standards; the second group of naming rules; criticism of Arabic dictionaries; classical Arabic sources', 'Too specialised for a first handbook, or too detailed for beginners.'],
  ['Borrowing from a dead language, a living language or other fields (cranium, internet, McDonaldization)', 'Borrowing is taught elsewhere, as a translation procedure (Chapter 13) and a way to make a word (Chapter 17), with other examples.'],
  ['Literal versus sense translation of terms; the definition of metaphor', 'Covered in the handbook’s own words in Chapter 11 and Chapter 12.'],
  ['Idioms such as _put a bug in your ear_, _dish the dirt_, _tie one on_, _three sheets to the wind_, _lays rubber_ (most of her 62)', 'Left out because they are mostly American slang, informal, about drinking, or unclear as written; Chapter 9 keeps to a short list of common idioms.'],
  ['_Walk in the park_, _make a long story short_, _born with a silver spoon_', 'Common, but duplicates: _a piece of cake_, _in a nutshell_ and the other idioms in Chapter 9 already cover them.'],
  ['General versus special language; terminology versus lexicography', 'Only the slide titles were in the text we have, and the topic is not needed at beginner level.'],
  ['How to cite references in English and Arabic', 'The handbook has no citing guide; its References list follows APA style.'],
  ['Course details on the title slide; the value of terminology; factors that shape terminology translation', 'Not teaching content, or not needed at beginner level.'],
  ['Translation Texts document; stylistics summary', 'Not received.'],
], [55, 45]],
['h2', '5.5 Added by Shaikha Alkhaldi to her chapter'],
['p', 'UNTERM and Arabterm, a sample term list, medical examples (_allergic_, _allergen_, _contact eczema_), the research steps from Shaikha Alkhaldi’s terminology class notes (see Section 7), and the Damascus academy and the Coordination Bureau of Arabization in Rabat.'],

// ================= SAMIUALLAH =================
['h1', '6. Samiuallah Mohammad'],
['p', 'Material received: the typed version of the audiovisual translation notes (see Section 4), the first draft (Draft_one), the plan and recommendations (Latest updates and thoughts), the 180 course notes (typed and scanned), the Translation 1 notes, the notes on Farghal & Shunnaq, the Text Analysis Model, the text {{الترجمة: ماهيتها وكيفيتها}}, the framework document and the main document.'],
['h2', '6.1 What was received'],
['ul', ['**The first draft:** his course notes arranged under 25 headings; five of the headings had no text.', '**The plan and recommendations:** a list of 38 requests (once repeats are merged) for the handbook.', '**Framework and layout instructions:** 18 points on structure, exercises, layout, citation and a beginner level.', '**The 180 course notes,** typed and scanned.', '**The Translation 1 notes:** strategies, tips and Arabic–English differences.', '**Notes on Farghal & Shunnaq (2011):** the notes and exercises he took from the book.', '**The Text Analysis Model:** a three-step model based on Fairclough.', '**A scanned Arabic text** ({{الترجمة: ماهيتها وكيفيتها}}): 13 pages on good translation, idioms and poetry, with no author or publication details.']],
['h2', '6.2 What was taken, and where'],
['p', '**The first draft.** Its headings became the backbone of the handbook.'],
['table', ['What', 'Where in the handbook'], [['Definitions: translation as transferring meaning (quoted, with Newmark 1988) and as approximation; the abbreviations TS, SL, TL, SLC, TLC with Arabic', 'Chapter 1, Steps 1–2; Words to remember; Abbreviations'], ['Aims of the book; what a translator needs; commissioned and self-initiated translators', 'Preface; Chapter 1, Steps 4–5'], ['Arabic and English: verbs first as a tendency; long Arabic sentences; synonyms ({{شجاعٌ مِغوار}} → _very brave_); register; four common challenges; the _He is in bed_ table', 'Chapter 4, Steps 1–5'], ['Form and meaning; changing the word class (_He is a heavy smoker_); Blair as Bush’s _poodle_', 'Chapter 5'], ['Denotation and connotation (_die_, _pass away_, _kick the bucket_; _steed_, _horse_); sentence meaning and speaker’s meaning ({{أشعر بالحر}})', 'Chapter 6, Steps 1–2'], ['Context; homonymy and polysemy ({{عين}}, {{تطهير}})', 'Chapter 7'], ['Collocation (_pay attention_; {{تعاون وثيق}}); “idiom” examples that were really collocations', 'Chapter 8'], ['Idioms: the definition, _raining cats and dogs_, _over the moon_, _a piece of cake_, _to roll up one’s sleeves_', 'Chapter 9'], ['Equivalence: the three types; _dead letter_ → {{حبراً على ورق}}; _think outside the box_', 'Chapter 10; Chapter 14, Step 1'], ['Literal and free translation; metaphor and simile (_He is a lion_); {{غيضٌ من فيض}}', 'Chapters 11 and 12'], ['Strategies: functional, cultural substitution ({{هما كقيس وليلى}}), addition, omission, explanation, _jet lag_', 'Chapters 13 and 14'], ['Cultural approximation and descriptive translation: _the test in the bag_, _mocktail_, UK and US titles, {{زكاة}}, _sectioned_, {{عطوة}}', 'Chapters 15 and 16'], ['Lexical creation: the five methods; _shadow government_, _blog_, _cybersecurity_, _cancel culture_', 'Chapter 17'], ['Text analysis with the eight-question checklist and a news-report example; commentary; post-editing; tips on titles', 'Chapters 18, 25, 22 and 2'], ['The five empty headings: how to use the book, terminology, machine translation, glossary, references', 'Written in full: Start here; Chapters 21 and 22; Glossary (113 terms); References (42 entries) and Further reading']], [58, 42]],
['p', '**The plan.** Requests marked “partly” were met in part.'],
['table', ['What was asked', 'Where in the handbook'], [['Organise the material, remove repetition (done)', 'Whole handbook: equivalence, denotation and connotation, collocation, idioms and descriptive translation each appear once'], ['Missing strategies and types of translation; a chapter on the seven procedures (done)', 'Chapters 1, 11, 14 (Steps 3–5), 26; Chapter 13'], ['Key concepts in every chapter; a glossary of all terms (glossary partly)', 'Words to remember in every chapter; Glossary (some terms used only in the text are missing)'], ['New chapters: machine translation, text analysis, commentary, dictionaries, terminology; a risk matrix (done)', 'Chapters 22, 18, 25, 3, 21 and 24'], ['Tips, the three questions (client, purpose, audience), checklists, common mistakes, an answer key (done)', 'Chapters 2, 18 (Step 4) and 23; Try it and Check your answers in every chapter'], ['Genres with examples; poetry; news texts (partly)', 'Chapters 19, 15, 2 and 18: eight genres, seven with a translated example; no full published article'], ['Fairclough’s relational model (partly)', 'Chapter 18, Step 3, as two levels; Chapter 20, Step 2, as three questions'], ['A final practice section; references for the course materials (partly)', 'Put it all together; References, with course materials cited as the Translation Team’s notes']], [50, 50]],
['p', '**Framework instructions.** Followed: principles first, then examples, in short numbered steps; Try it questions in every chapter; a contents page; quotation marks and citations for borrowed text; no book summaries; a beginner level. Two points differ: the abbreviations are at the back, and the answers are inside each chapter.'],
['p', '**Course notes and model.**'],
['table', ['What', 'Where in the handbook'], [['180 notes: mostly the source of the draft; also {{ثكلى}} (_a bereaved mother_), _to be in the red_ and _Business is business_ ({{الشغل شغل}})', 'Chapter 6, Step 3; Chapter 9, Steps 3–4'], ['Translation 1 notes: five strategies with examples; _the Fed_ for addition ({{الإطناب}}); {{كالمستجير من الرمضاء بالنار}}; the minefield tip', 'Chapter 14, Steps 1–2; Chapter 9, Step 4; Chapter 2'], ['Farghal & Shunnaq: _Ali often goes to bed early_, _The students are in the laboratory_; _heavy rain_ ({{مطر غزير}}); _deliver_; three collocations of {{يقطع}}', 'Chapter 4, Steps 1–2; Chapter 8, Try it, Steps 2–3'], ['Farghal & Shunnaq: _A burnt child dreads the fire_; _garage_; _computer_ and _technology_; {{خال}} and {{عمّ}} as _uncle_', 'Chapters 13, 17 and 14 (Step 4); cited as (Farghal & Shunnaq, 1999/2011) in Chapters 4, 10, 12 and 15–17'], ['Text Analysis Model: three phases; linguistic level (words, grammar, meaning, word forms, sound; text, other texts, point of view); external level; quality check; Fairclough (2003)', 'Chapter 18, Steps 1, 3 and 5; Chapter 25, Step 2; References'], ['Scanned text: _He looks blue_, _I will go bananas_', 'Chapter 9, Step 3, cited as the team’s course materials']], [58, 42]],
['h2', '6.3 What was edited or corrected'],
['ul', ['Every section was rewritten as guided steps. Definitions that the draft gave two or three times (idioms, equivalence, denotation and connotation, descriptive translation) were merged.', 'Several Arabic terms were changed: form {{الشكل}} (was {{البناء}}); lexical creation {{التوليد المعجمي}} (was {{النحت المعجمي}}); lexicalised {{المَعْجَمة}} (was {{التعجيم}}); the labels {{المعنى المعجمي}} and {{المعنى الإيحائي}}.', '_Dead letter_ now reads “has remained a dead letter”, and its ideational Arabic was reworded.', 'Colloquial Arabic was replaced by one standard expression each (for example {{نشيطٌ كالنحلة}}), and the suicide-bomber example was made neutral.', 'Notes written with only the Arabic were given English equivalents (_he drew his sword_, _I am worried_).', 'Zakat is now described as a share of savings and wealth above a minimum, not of income.']],
['h2', 'Errors in the first draft that were corrected'],
['ul', ['“Died” had the Arabic for “killed”: corrected.', '“Kick the bucket” was given with an insulting phrase ({{يموت كالحقير}}): it is now used to show that the idiom is informal and humorous, not insulting (Chapter 6).', 'A line said form is more important than meaning: reversed, since meaning comes first.', '“Bush’s puppy”: the press said “poodle”.', '“Mark my words” was translated as a promise: corrected to {{تذكّر كلامي}}.', 'The rule that Arabic always starts with the verb: corrected (Arabic often starts with the verb, but not always).', 'The Arabic equivalent of “is”: corrected.', '_Sam ate the cake_ had been translated with “the apple” ({{التفاحة}}): corrected.', '_The Home Office_ had been translated as a minister ({{وزير}}): corrected to a ministry ({{وزارة}}).', 'Some “idiom” examples were really collocations: moved to Chapter 8.', 'Colloquial Egyptian expressions were replaced with formal ones, and examples that took a political or religious position were rewritten to stay neutral.']],
['h2', '6.4 What was not taken, and why'],
['table', ['Not taken', 'Why'], [['The communication model and intralingual communication; “Why is meaning complex?”; Arabic as derivational and English as compounding; non-stative verbs and sentence types; creative and decorative metaphors; nursery rhymes; précis translation', 'Too theoretical or technical for a beginner handbook; the useful idea is kept in plain words where possible'], ['Blending, clippings, infixation, frame-modification, re-modelling, Al-ta’reed, monitoring, intrinsic and extrinsic managing; the poetic-sense pages of the scanned text', 'Too advanced for beginners'], ['“KUNA has biased views”; the Clinton impeachment examples; the political examples on managing and manipulation; {{كل نفس ذائقة الموت}} as an equivalent; {{استشهد}} as a connotation', 'Not neutral: a named organisation or person, a political or religious position, or a Qur’anic verse used as a translation equivalent'], ['“Principles = Foundations”; “translation also means to politicize”; _mule_ as a synonym of _horse_; _kill_ vs _assassinated_; _Valentine’s Day_ as a calque; tribocracy and other invented words; “most of the time, literal translation fails”; _break the ice_ and _she is in the clouds_ from the scanned text', 'Wrong or unclear: the meaning is unclear, the word is wrong, the example does not show the point, or the book shows the opposite'], ['The “74 fields” of the Jordanian academy; {{يموت كالحقير}} and _kick the chair_ = {{انتحر}}; {{الاستتابة}}; the lists in Exercise 31', 'Could not be verified: no source confirms them, or the notes are unclear or inconsistent'], ['Farghal & Shunnaq: _It’s raining_ as speaker meaning; the margin proverbs; adaptation vs free translation; scanned pages on dictionaries, the translator’s requirements and common Arabic errors', 'Duplicate: the same points are already in the chapters, from the 180 notes or the team’s notes'], ['Exercise lists (_a readable book_, _heavy smoker, heavy sleep_, the proverbs of Exercise 5, the ambiguous sentences, _foot_, the High Street text); {{بناء}}; _Every Jack has his Jill_; Yin-Yang; _co-wife_; scanned idioms 6 and 8–13', 'Left out for space; some could form an exercise set on the website'], ['Most pages of the scanned Arabic text', 'Cannot be cited: the pages give no author or publication details'], ['Sample analyses (news, speech, climate change); the Analysis and 386 texts; the supervisor’s framework; practice texts from Masooma; a note on future editions and an Arabic version; a feedback step', 'Not received, or removed to keep the handbook short, or a step for after the first draft']], [55, 45]],

// ================= SHAIKHAH =================
['h1', '7. Shaikha Alkhaldi'],
['p', 'This section lists the work done on the handbook by Shaikha Alkhaldi, with the place in the book where each piece can be found and the reason for it. It covers her own material, the structure of the book, the sections written for it, the examples, the checking, and the design.'],

['h2', '7.1 Her own material'],
['p', 'Her study notes (her course slides) were used in the chapters below. Each was rewritten in plain English, with an example before its technical name.'],
['table', ['Her notes', 'Where it is now'], [
  ['The three kinds of translation; the translator as a reader before being a writer', 'Chapter 1'],
  ['_be_, _do_ and _have_; the dual (for example {{المحكمان}}); the gender of _I_ and _you_; _She has her pills on time_', 'Chapter 4'],
  ['Lexical gaps ({{ثكلى}}), false equivalents, rare words', 'Chapter 6'],
  ['{{خط}}, a word with several meanings', 'Chapter 7'],
  ['One verb with several partners (_deliver a letter, a speech, a verdict_)', 'Chapter 8'],
  ['Fixed expressions; how to spot an idiom; five ways to translate one; three more idioms', 'Chapter 9'],
  ['The word-level strategies: a more general word, a more neutral word, paraphrase, a loan word plus explanation; Arabic words borrowed into English (_algebra_, _algorithm_)', 'Chapter 14'],
  ['Arabicisation ({{استراتيجية}}, {{تكنولوجيا}})', 'Chapter 17'],
  ['News headlines; the inverted pyramid; hard and soft news; technical and literary texts', 'Chapter 19'],
  ['Medical terms (_allergic_, _allergen_, _contact eczema_)', 'Chapter 21'],
  ['Translation memory, termbases, the development of machine translation, localisation', 'Chapter 22'],
  ['The Arabic dubbing of _The Simpsons_', 'Chapter 26'],
], [68, 32]],
['p', 'Her notes from the terminology course she took were used in Chapter 21, Steps 1 and 3 to 5: a term can be several words; read about a new field and ask a specialist; check a term’s parts against its context; confirm an equivalent in an original Arabic text; write a one-sentence definition; some concepts have two accepted names.'],

['h2', '7.2 Structure of the book'],
['ul', [
  '**The order of the book.** The 9 parts and 27 chapters run from easy to hard, so that each chapter uses only what the reader has already met. The dictionaries chapter was moved into Part 1 (Chapter 3), because a beginner needs a first tool before anything else.',
  '**One pattern for every chapter.** Each chapter opens with **Where we are**, teaches in numbered steps (the problem first, then the solution), gives questions to **Try it** with answers under **Check your answers**, and closes with **Remember**, **Words to remember** and **Next**, which names the following chapter. The pattern lets a beginner know what to expect and never lose the path.',
  '**The glossary.** The 113 terms come from the Words to remember boxes, in alphabetical order, each with its Arabic equivalent, definition and chapter. Where a term has two Arabic equivalents, they are joined with {{أو}} and the first is the preferred one.',
  '**The back matter.** The list of abbreviations, a Further reading list of five books, and the References (42 entries).',
  '**The contents page and running heads**, so that a reader always knows the part and the chapter.',
]],

['h2', '7.3 Sections written for the handbook'],
['p', 'The following were written where the team’s material did not cover a topic that the plan asked for. Each uses published sources, cited in brackets.'],
['table', ['Section', 'Where it is now', 'Main sources'], [
  ['Start here: translation in daily life, the House of Wisdom, the four steps of a translation, the way through the book', 'Front matter', '—'],
  ['Printed and digital dictionaries', 'Chapter 3', 'Johnson; Wehr; the dictionaries named in the chapter'],
  ['Communicative translation, the middle way between literal and free translation', 'Chapter 11, Step 4', 'Newmark (1988)'],
  ['The seven translation procedures', 'Chapter 13', 'Vinay & Darbelnet (1958/1995); Newmark (1988)'],
  ['Explicitation and implicitation; domestication and foreignisation; compensation', 'Chapter 14, Steps 3 to 5', 'Vinay & Darbelnet; Venuti (1995); Dickins et al. (2016)'],
  ['Words and points of view', 'Chapter 20', 'Fairclough (1992)'],
  ['Machine translation: what it does, its typical mistakes, correcting its output', 'Chapter 22', 'Kenny (2022)'],
  ['Revision and common mistakes', 'Chapter 23', 'Mossop (2014)'],
  ['Subtitle timing and spotting, SDH, a five-step method, rules for Arabic subtitles', 'Chapter 27', 'Díaz Cintas & Remael (2021)'],
  ['Your journey continues: daily habits, learning from real translations, where a translator can go next', 'End of the book', '—'],
], [46, 24, 30]],

['h2', '7.4 Examples and Arabic terms'],
['ul', [
  '**Opening example.** Start here opens with a real translation decision from a news report: _The government came under pressure to reconsider the decision._ → {{تعرّضت الحكومة لضغوط لإعادة النظر في القرار}}, against the word-for-word version. It shows a beginner in one look what a translator does: understand, decide and rebuild.',
  '**Every example was checked** against the team’s documents and her notes. Examples from the team were kept, with their errors corrected (Section 6.3). Examples that were weak were replaced, preferably with examples from the team’s files.',
  '**Examples added** where the team’s material had none: _the White House_ → {{البيت الأبيض}} (an established equivalent), _You can’t miss it_ → {{ستجده بسهولة}}, _Parking for residents only_ → {{ممنوع الوقوف لغير السكان}}, and the comparison in Chapter 11 of a too literal, a natural and a too free translation.',
  '**Three challenge questions** (Chapters 10, 14 and 15), each with a real sentence and two possible translations: the reader chooses the one that suits the audience and explains why.',
  '**Subtitling examples.** The subtitling examples are two famous, cited film lines, each explained: _The Godfather_ (condensing through Arabic syntax) and _Gone with the Wind_ (softening strong language).',
  '**Kuwaiti expressions.** Six expressions were chosen from the Kuwaiti expressions dictionary, following the proposal of Loulwah Bin Saeed (Section 4.2), and placed in Chapters 9, 15 and 27, with their English equivalents.',
  '**Arabic terms corrected.** Genre → {{نوع النص}}; Ideology → {{المنظومة الفكرية (الأيديولوجيا)}}; Loaded word → {{كلمة مشحونة دلالياً}}.',
  '**Rules framed as tendencies.** Statements such as “prefer a verbal sentence” and “use Modern Standard Arabic” now say that the text type, the audience, the purpose and the medium can change the choice (Chapters 4, 10, 20, 22 and 27); the subtitle conventions are marked as conventions, not rules.',
  '**Try it made clearer.** Every Try it opens with a line saying what it is for, its questions name the skill being practised, and its answers explain why.',
]],

['h2', '7.5 Guides and features for the reader'],
['ul', [
  '**The translator’s workflow** (end of Part 1): seven steps from reading to delivery, each linked to its chapter, with Do and Don’t boxes.',
  '**When in doubt** (before the closing section): what to do with an unknown word, with two possible translations, and with an answer from a machine.',
  '**Translation quality checklist** (end of Part 8): meaning, language, terms and names, details, and the final reading.',
  '**Put it all together** (after Chapter 27): one short press release taken through every step of the book, from the brief to a short commentary.',
  '**Ten “Did you know?” boxes** with short, true stories (the Rosetta Stone; the Universal Declaration of Human Rights; {{كتاب العين}}; Arabic numerals; the verb _run_; the journey of _coffee_; the Damascus academy; the 1954 machine-translation demonstration; the _Mars Climate Orbiter_; silent-film intertitles), so that the reader sees why translation matters. The intertitles come from the audiovisual translation notes.',
]],

['h2', '7.6 Checking and corrections'],
['ul', [
  'The whole book was reviewed in two full rounds, with 192 and then 102 corrections: definitions and concepts, Arabic grammar and terminology, examples that did not illustrate their point, cross-references, English, neutrality and citations.',
  'All 42 references and every direct quotation were checked twice against published information (authors, years, titles, publishers, DOIs and page numbers). Every citation in the text is matched to an entry in the References.',
  'After each round, every Arabic example was checked, so that none was lost or changed by mistake.',
  'Chapter numbers and cross-references were updated after the order of the book changed.',
  'Material tied to a date, an event or a product was reduced where possible, so that the book can be used year after year.',
]],

['h2', '7.7 Design and website'],
['ul', [
  'The two covers (Midnight and Light), designed with the club’s own logo.',
  'The page layout: light pages, a running head, roman numerals for the opening pages, and a size of 98 pages.',
  'The QR code on the back cover and on the last page of the book, which leads to the Translation Team’s website.',
  'The Translation Team’s website, which she created.',
]],

['h2', '7.8 Her proposals not taken, and why'],
['table', ['Not taken', 'Why'], [
  ['The parallel-texts step (“Intertextual Mapping Protocol”) and the ethics checklist (“Invisible Translator” audit)', 'They need texts and practice; they suit the website or a later edition. Parallel texts are mentioned in Your journey continues.'],
  ['“Dynamic Syntactic Restructuring” as a separate module', 'Partly covered by word order and verb-first sentences in Chapter 4.'],
  ['Quick-reference genre checklists for each text type', 'Replaced by one Translation quality checklist (end of Part 8) and the genre guidance in Chapter 19.'],
  ['The website’s Practice Arena and other features', 'They belong on the website, which carries what changes; the book carries what lasts.'],
], [45, 55]],

['h2', '7.9 Course slides (15 decks)'],
['p', 'Fifteen slide decks, from the introduction to translation studies to localization and translation technology. Most items were shortened to one idea and re-explained with new examples. The decks give a sense of the course, and the handbook keeps the practical core.'],
['p', '**Taken, and where**'],
['table', ['Topic and examples', 'Where'], [
['Written translation versus interpreting; the wider meaning of translation (Jakobson); the aim of translation (Newmark); the translator as a reader before a writer', 'Chapter 1, Steps 1, 3 and 4'],
['The Rosetta Stone, told as a short true story', 'Chapter 1, Did you know? box'],
['Myths: translation is not just words; two languages are not enough; a translator learns the topic and both cultures', 'Start here; Chapter 1, Step 4; Chapter 2'],
['Denotation and connotation (_die_ and _pass away_); lexical gaps ({{ثكلى}}); a rare measure ({{شبر}}); {{خط}}', 'Chapters 6 and 7'],
['Word-level strategies: generalisation ({{خال}}, {{عمّ}} → _uncle_), cultural substitution, loan word (_waqf_), paraphrase, omission', 'Chapter 14, Steps 1 to 4'],
['Collocation (_pay a visit_ → {{يقوم بزيارة}}); idioms and five strategies (Baker); fixed expressions', 'Chapters 8 and 9'],
['Grammar: the Arabic dual, gender of _I_ and _you_, _be_, _do_ and _have_', 'Chapter 4, Steps 2 and 3'],
['News: headline, lead, inverted pyramid, headline grammar; literary style and dialect', 'Chapter 19, Steps 3 and 4'],
['Same term in different fields (_depression_); medical terms; terminology and termbases', 'Chapters 19 and 21'],
['Machine translation, translation memory and localization (_The Simpsons_ as {{آل شمشون}}); purpose decides how to translate (Skopos)', 'Chapters 22 and 26'],
], [68, 32]],
['p', '**Not taken, and why**'],
['table', ['Not taken', 'Why'], [
['The history and theory of the field: Holmes’s map, Descriptive Translation Studies, the Cultural Turn, poly-system theory, the Middle Ages and the Renaissance; the four kinds of lexical meaning; tense, aspect and voice', 'Too theoretical for a beginner handbook.'],
['Morphemes, level of specificity, features of literary and technical language, the hourglass and narrative news structures, why idioms are hard', 'Too technical, or not needed at beginner level.'],
['The five phases of translation; literal versus free translation', 'Duplicates: the handbook has its own four steps (Start here) and Chapter 11.'],
['The myth that the need for translation is decreasing', 'The statistic had no source in the slides.'],
['Extra examples: _shrug_, _bury_, the Arabic way of telling time, the Hohola house fire, more headlines', 'Left out for space; one example per rule was kept.'],
['Class exercises and quizzes (Google Scholar, _Jane Eyre_, seven headlines)', 'Not teaching content; the handbook has its own Try it questions.'],
['Six exercise slides and the _Harry Potter_ slide', 'They came out empty when converted, so they could not be checked.'],
], [62, 38]],
['h2', '7.10 Terminology class notes (12 decks)'],
['p', 'Twelve sets of class notes on terminology, from the first weeks (what terminology is, terms and concepts) to term research, records and analysis. They describe the work of a professional terminologist. The handbook takes only what a student translator can use.'],
['p', '**Taken, and where**'],
['table', ['Topic and examples', 'Where'], [
['A term can be several words, translated as one unit (_network security_)', 'Chapter 21, Step 1'],
['Search for an accepted term first; create one only if none exists; the context decides (_blackboard_)', 'Chapter 17, Step 3; Chapter 21, Step 3'],
['Read a short introduction to a new field; confirm the equivalent in an Arabic text written by specialists; ask the client or a specialist', 'Chapter 21, Step 3'],
['Definition by class and difference, in one sentence (the handbook’s example is _thermometer_)', 'Chapter 21, Step 4'],
['A source for each term in the term list', 'Chapter 21, Step 4'],
['One concept, two accepted names (_aerial_ and _antenna_, with {{هوائي}}, {{حاسوب}} and {{كمبيوتر}})', 'Chapter 21, Step 5'],
['One word, a different term in each field (_depression_)', 'Chapter 19, Step 4'],
], [68, 32]],
['p', '**Not taken, and why**'],
['table', ['Not taken', 'Why'], [
['Signifier and signified, the arbitrary link between term and concept, classes of concepts, terminology versus semantics and lexicography, the history of the discipline', 'Too theoretical for beginners.'],
['Rules of definition, partition and operational definitions, standardisation, comparative terminology, textual match', 'Too advanced for beginners.'],
['The 11 fields of a monolingual record, the 18 of a bilingual record, entry rules, typographic clues to terms', 'Record formats and analysis are too detailed; a termbase entry has five parts (Chapter 21, Step 4).'],
['The six stages of subject-field research and the six steps of term research', 'Too advanced; the handbook works term by term with its own routine (Chapter 21, Step 3).'],
['Term formation in English, reasons for new terms', 'About English; Chapter 17 gives five ways to make Arabic words.'],
['Class exercises (Apple Watch pages, nuclear weapons text, _bank_, _mouse_, _cell_)', 'Class work; not suited to print.'],
], [62, 38]],
['h2', '7.11 Framework proposals'],
['p', 'Her proposals for the handbook, in eleven parts: aims, guides and checklists, practical modules, and a companion website.'],
['p', '**Taken, and where**'],
['table', ['Proposal', 'Where'], [
['A practical, engaging guide for beginners', 'Preface; Start here'],
['Breaking the Literal Trap (real legal, technical and news examples)', 'Chapters 1, 11 and 19, inside the chapters they illustrate'],
['The Terminology Guide (Arabicisation, transliteration)', 'Chapters 16, 17 and 21; the book uses {{التعريب}} and {{النقل الصوتي}}'],
['Genre checklists, and the Common Pitfalls Clinic', 'Chapter 19; Chapter 23 (weak version, then better version); final checklist'],
['Translation Brief (Skopos)', 'Chapter 2: three questions; Chapter 26'],
['Risk Assessment Matrix', 'Chapter 24 (table of risk areas)'],
['Corpora and digital tools', 'Chapters 3, 21 and 22: UNTERM and Arabterm'],
['Restructuring syntax; pragmatic shift (partly)', 'Chapters 4, 5, 6, 9, 15 and 23'],
['Companion website: QR code and address', 'Back cover; last page; Your journey continues'],
], [56, 44]],
['p', '**Not taken, and why**'],
['table', ['Not taken', 'Why'], [
['The Practice Arena: Text of the Week, Idiom Arena, De-Anglicize It, Before and After, badges and leaderboard, the Workshop Companion', 'Need online submission, timers or live workshops, so they belong on the website. The book has Try it questions and one practice text.'],
['The Library and the case for the website', 'Belong on the website; the book has its own glossary.'],
['The Invisible Translator Ethical Audit', 'Needs reflection and practice; suits the website or a later edition.'],
['The Intertextual Mapping Protocol (step by step)', 'Only the habit of checking real target-language texts is kept.'],
], [62, 38]],

// ================= WHOLE BOOK =================
['h1p', '8. Removed from the whole draft, and why'],
['table', ['Removed', 'Why'], [
  ['The practice section at three levels and its answer key', 'Too long for a handbook; each chapter keeps its Try it questions with answers.'],
  ['The four checklists at the end', 'They repeated the chapter summaries.'],
  ['The note on future editions and the Arabic version', 'A printed book cannot keep being updated; the website carries later material.'],
  ['Most scholars’ names in the running text', 'Easier reading; every idea keeps its citation in brackets.'],
  ['References to the courses and the lecturers', 'The handbook is meant to be used on its own.'],
  ['Part descriptions and about a third of the running text', 'Repetition and long explanations made the pages heavy.'],
  ['Most examples tied to a date or event', 'So that the book stays valid every year.'],
  ['Placeholders, unconfirmed reviewers’ names and mentions of the Guild Season', 'Not final or not confirmed.'],
  ['The acknowledgements and the Contributors list', 'Left out of this draft; contributors will be credited in the final version.'],
], [42, 58]],

['h1', '9. Still open for the team'],
['p', 'Because this is a draft, the following need the team’s decision:'],
['redul', [
  'Whether the material not yet received should go into this edition: Loulwah’s Principles of Translation notes, the Gamal article and AVT Theory; Masooma’s Translation Texts and stylistics summary; the three sample analyses.',
  'Who shared the Kuwaiti expressions dictionary, and its author, publisher and year, so that it can be cited in full.',
  'The author and publication details of the text {{الترجمة: ماهيتها وكيفيتها}}, so that the two idioms taken from it can be cited in full.',
  'The page size: B5 now; A5 was the size of the model book.',
  'Before printing: a full read by a native Arabic specialist; checking the ten Did you know? facts and the open reference points listed in the Final Report.',
]],
];
