// Contributions Report: a working report by Shaikha Alkhaldi on how each member's material was used in the draft handbook.
module.exports = [

['h1', '1. About this report'],
['ul', [
  'This working report explains how each team member’s material was used in the draft handbook: what was taken, what was edited, what was left out, and why. Section 7 lists the work done on the handbook itself, under the name of Shaikha Alkhaldi.',
  'The handbook it describes is a **draft for the team’s review**, not the final version. Every decision below can be discussed and changed.',
  'The report follows the current draft: two editions (Midnight and Light) with the same content, 98 pages, 9 parts and 27 chapters, an opening section (**Start here**) and a closing section (**Your journey continues**).',
  'Members are listed in alphabetical order. Chapter numbers refer to the current draft.',
  'The item-by-item record of every document is in the Appendix: The Team’s Documents.',
]],

['h1', '2. How material was chosen'],
['p', 'Every point was judged by two questions: does a beginner need it, and is it correct? This led to six working rules:'],
['ol', [
  'Each idea is explained with an example before it is named, in numbered steps.',
  'Each topic appears once, in the chapter where it belongs, even when several members covered it. As the framework agreed, material that appeared in several members’ notes was kept first, and material from one member was reviewed case by case.',
  'Anything that could not be checked was left out rather than printed.',
  'Examples that took a political or religious position were rewritten or left out.',
  'History and specialist theory were kept to a minimum; they are available in other books.',
  'Every idea taken from a published work is cited in brackets, and listed in the References.',
]],

['h1', '3. Where each chapter comes from'],
['p', 'The table shows the main source of each part of the draft, and what else was added to it.'],
['table', ['Section', 'Main source', 'Also added'], [
  ['Start here', 'Written by Shaikha Alkhaldi', 'The news-report example (_came under pressure_); the House of Wisdom; the four steps'],
  ['1 Translation and the translator', 'Samiuallah Mohammad (draft)', 'Shaikha’s notes: three kinds of translation, the translator as a reader; the Rosetta Stone'],
  ['2 Tips, advice and preparation', 'Masooma Almesri (idea); Samiuallah (draft tips and plan)', 'Shaikha’s framework: the three questions (client, purpose, audience); a worked first translation'],
  ['3 Printed and digital dictionaries', 'Loulwah Bin Saeed (idea); Samiuallah (plan)', 'Written by Shaikha Alkhaldi from published sources; {{كتاب العين}}'],
  ['4 English and Arabic: key differences', 'Samiuallah (draft; 180, Translation 1 and Farghal & Shunnaq notes)', 'Shaikha’s notes: _be_, _do_, _have_, the dual, gender of _I_ and _you_; Arabic numerals'],
  ['5 Form and meaning', 'Samiuallah (draft)', '—'],
  ['6 Types of meaning', 'Samiuallah (draft)', 'Shaikha’s notes: lexical gaps, false equivalents, rare words'],
  ['7 Context', 'Samiuallah (draft)', 'Shaikha’s notes: {{خط}}; the verb _run_'],
  ['8 Collocation', 'Samiuallah (draft)', 'Shaikha’s notes: _deliver_; Farghal & Shunnaq notes: _weak coffee_, _a rough sea_, the collocations of {{يقطع}}'],
  ['9 Idioms, proverbs and fixed expressions', 'Samiuallah (draft)', 'Shaikha’s notes: fixed expressions, spotting idioms, five ways to translate them; 180 notes and {{الترجمة: ماهيتها وكيفيتها}}: three idioms; Kuwaiti expressions from the Kuwaiti dictionary (Loulwah’s proposal)'],
  ['10 Equivalence', 'Samiuallah (draft)', 'Citation of Farghal & Shunnaq'],
  ['11 Literal and free translation', 'Samiuallah (draft)', 'Communicative translation (requested in the Teams chat)'],
  ['12 Metaphoric translation', 'Samiuallah (draft)', 'Masooma’s slides: {{عقارب الساعة}}, _a throbbing headache_'],
  ['13 The seven translation procedures', 'Samiuallah (plan); written by Shaikha Alkhaldi from published sources', 'Examples from Samiuallah’s Farghal & Shunnaq notes and draft: _shadow government_, _My friend speaks German fluently_, _A burnt child dreads the fire_, _garage_'],
  ['14 Translation strategies', 'Samiuallah (draft and Translation 1 notes)', 'Explicitation and implicitation (Teams chat); further strategies; Shaikha’s notes: Arabic words in English'],
  ['15 Cultural approximation', 'Samiuallah (draft)', 'Citation of Farghal & Shunnaq'],
  ['16 Descriptive translation', 'Samiuallah (draft)', 'Citation of Farghal & Shunnaq'],
  ['17 Lexical creation', 'Samiuallah (draft)', 'Shaikha’s notes: Arabicisation examples; Masooma’s slides: {{الاستمطار}}, {{قطار}}, affixes; the journey of _coffee_'],
  ['18 Text analysis', 'Samiuallah (draft and Text Analysis Model)', '—'],
  ['19 Text types and genres', 'Samiuallah (plan); Shaikha (framework)', 'Shaikha’s notes: news headlines, the inverted pyramid, technical and literary texts'],
  ['20 Words and points of view', 'Samiuallah (plan: the relational model; draft: the _suicide bomber_ example)', 'Written by Shaikha Alkhaldi from published sources'],
  ['21 Terminology', 'Masooma and Samiuallah (terminology material from Masooma’s slides)', 'Shaikha’s terminology class notes: the research steps; Shaikha’s notes: medical examples; UNTERM, Arabterm, a sample term list; the Damascus academy'],
  ['22 Machine translation', 'Samiuallah (draft: post-editing; plan); Loulwah (framework: a practical guide to digital tools)', 'Shaikha’s notes: translation memory, CAT tools, localisation; the 1954 demonstration'],
  ['23 Revision and common mistakes', 'Masooma (idea); Samiuallah (plan); Shaikha (framework)', 'Written by Shaikha Alkhaldi from published sources'],
  ['24 Interlingual risk assessment', 'Shaikha (framework)', 'The _Mars Climate Orbiter_'],
  ['25 Translation commentary', 'Samiuallah (draft and Text Analysis Model)', '—'],
  ['26 Introduction to audiovisual translation', 'Loulwah (AVT notes)', 'Shaikha’s notes: the Arabic dubbing of _The Simpsons_; the AVT notes: silent-film intertitles (a Did you know? box)'],
  ['27 Subtitling', 'Loulwah (AVT notes)', 'Subtitle timing, SDH, a five-step method, rules for Arabic subtitles'],
  ['Your journey continues', 'Written by Shaikha Alkhaldi', '—'],
], [30, 32, 38]],

// ================= LOULWAH =================
['h1', '4. Loulwah Bin Saeed'],
['p', 'Material received: the audiovisual translation notes (Intro to AVT and AVT 2), idiom notes, and her suggestion to include dictionaries. Her Principles of Translation notes, the Gamal article and the AVT Theory file have not yet been received, and her other notes were lost.'],
['p', 'A typed and organised version of the same notes (Audiovisual Translation.docx), posted by Samiuallah Mohammad, was compared with Chapters 26 and 27. It contains no new material: everything suitable for beginners was already in the handbook, and the parts left out are the same as below. It still gives the old line length (32 to 41 characters), which the handbook corrects. The parts left out would suit the website, as Samiuallah Mohammad suggested.'],
['h2', '4.1 Taken into the handbook'],
['table', ['What was taken', 'Where it is now'], [
  ['Why audiovisual translation matters, and what makes it different from other translation', 'Chapter 26, Step 1'],
  ['The main types: subtitling, dubbing, voice-over and others', 'Chapter 26, Step 2'],
  ['Dubbing, and dubbing in the Arab world', 'Chapter 26'],
  ['Purpose comes first (Skopos theory)', 'Chapter 26; linked from Chapter 2'],
  ['The challenges of the field', 'Chapter 26'],
  ['Subtitles and their kinds (open and closed)', 'Chapter 27'],
  ['Words, images and sound work together', 'Chapter 27, Step 3'],
  ['Language variety: sociolect, slang, idiolect', 'Chapter 27, Step 3'],
  ['Cultural references and the subtitling strategies for them', 'Chapter 27, Step 4'],
  ['Taboo language and censorship', 'Chapter 27, Step 5'],
  ['The suggestion to include the dictionaries that helped the team and how to use them', 'Chapter 3, now in Part 1'],
  ['Her proposal of Kuwaiti expressions from a Kuwaiti dictionary: six expressions from _Muʿjam al-taʿābīr al-iṣṭilāḥiyya al-Kuwaytiyya al-muqārana_ ({{الحجي سهل}}, {{الحجي معاك ضايع}}, {{السالفة أكبر من جدي}}, {{الدموع أربع أربع}}, {{الشمس منين طالعة؟}}, {{العين أوسع من الدار}}), with their English equivalents', 'Chapter 9, Step 5; Chapters 15 and 27'],
  ['Her proposal of a practical guide, near the end of the book, to using digital tools and machine translation wisely', 'Chapter 22, Steps 5 and 6'],
], [62, 38]],
['h2', '4.2 Edited'],
['ul', [
  'The two overlapping lists of subtitling strategies were merged into one list of eight.',
  'The spelling of Vermeer, Díaz Cintas and Remael was corrected.',
  '“32 to 41 characters per line” was corrected to about 37 to 39, and up to 42 on streaming platforms.',
  '“Relies 100% on technology” became “depends heavily on technology”.',
  'The description of dubbing in the Arab world was corrected.',
]],
['h2', '4.3 Not taken, and why'],
['table', ['Not taken', 'Why'], [
  ['The history of the field', 'Not needed to start subtitling.'],
  ['Three of the four theories (descriptive translation studies, polysystem theory, reception studies)', 'Beyond a beginner’s level; Skopos theory is kept because it is practical.'],
  ['The summary on audiovisual translation in the Arab world', 'Kept short so that Part 9 stays practical.'],
  ['Minor types (free commentary, in-vision signing, fansubs, surtitles)', 'The list was kept to the main types.'],
  ['The YouTube links', 'Links stop working in a printed book.'],
  ['The quotation on “screen translation”', 'Not needed once the term was explained.'],
  ['The idiom notes', 'Several entries needed correcting (_my cup runneth over_, _rear-view mirror_, _just deserts_) or were incomplete, and most equivalents are colloquial.'],
], [45, 55]],
['h2', '4.4 Added by Shaikha Alkhaldi to her chapters'],
['p', 'Subtitle display time and spotting, subtitles for the deaf and hard of hearing (SDH), a five-step subtitling method, a worked example of shortening a line, rules for Arabic subtitles, first steps for beginners, and full reference entries for the published sources her notes already named (Díaz Cintas & Remael; Pedersen; Pérez-González; Gambier; Reiss & Vermeer).'],

// ================= MASOOMA =================
['h1', '5. Masooma Almesri'],
['p', 'Material received: the terminology slides (182), the terminology material selected from them with Samiuallah Mohammad, the TerminologyIdioms document, and her framework proposals: an opening chapter of tips, a glossary, a separate chapter on idioms, and a chapter on common mistakes. Her Translation Texts document (180 and 386 texts) and her stylistics summary have not yet been received.'],
['h2', '5.1 Taken into the handbook'],
['table', ['What was taken', 'Where it is now'], [
  ['The definition of terminology, and of a term', 'Chapter 21, Step 1'],
  ['The four short forms: initialisms, acronyms, abbreviations, clippings (with the same examples)', 'Chapter 21, Step 1'],
  ['The translator and the terminologist', 'Chapter 21, Step 2'],
  ['The Arabic language academies', 'Chapter 21, Step 2'],
  ['How to translate a term (meaning, origin, equivalent)', 'Chapter 21, Step 3'],
  ['What makes a good term; do not change an accepted term without good reason; avoid redundant terms ({{التطرّف الراديكالي}})', 'Chapter 21, Steps 3 and 5'],
  ['Termbases: what they are and what an entry contains', 'Chapter 21, Step 4'],
  ['Why terms must be managed; one term for one idea', 'Chapter 21, Step 5'],
  ['When dictionaries fail, think like a terminologist; a terminologist sometimes creates terms', 'Chapter 21, Step 3'],
  ['Metaphor in terms: {{عقارب الساعة}}; _a throbbing headache_', 'Chapter 12, Step 3'],
  ['Derivation and new meanings: {{الاستمطار}}, {{قطار}}; affix translation (_manageable_, _antibiotic_)', 'Chapter 17, Step 2'],
  ['The idea of an opening chapter that prepares students before they start', 'Chapter 2'],
  ['Her proposals of a glossary, a separate chapter on idioms, and a chapter on common mistakes', 'Glossary; Chapters 9 and 23'],
], [62, 38]],
['h2', '5.2 Edited'],
['ul', [
  'The chapter was rewritten in plain English and reduced to what a beginner needs.',
  'The definition of a terminologist and some historical details were corrected.',
  'The chapter cited no sources, so sources were added (Cabré, 1999; UNTERM; Arabterm).',
]],
['h2', '5.3 Not taken, and why'],
['table', ['Not taken', 'Why'], [
  ['The history of terminology, its schools and its periods', 'History is not needed to use terms well.'],
  ['Functions, points of view and user groups of terminology', 'Theory beyond a beginner’s level.'],
  ['Categories of terms by function, meaning and origin, and the types of borrowing', 'Too theoretical; the practical categories (short forms) are kept.'],
  ['Most of the nine rules for naming terms', 'The practical rules are kept in one sentence.'],
  ['The standardisation bodies (ISO, IEC, ITU) and types of standards', 'Too specialised for a first handbook.'],
  ['The academies’ detailed approval procedures', 'Too detailed; the academies themselves are kept.'],
  ['Terminography and the fields of a termbase entry', 'Reduced to one sentence on what an entry contains.'],
  ['The format for citing references', 'It belongs to the References style, not to the text.'],
  ['Most of the idiom list', 'Mostly American slang, some about drinking; the common idioms are already in Chapter 9.'],
], [45, 55]],
['h2', '5.4 Added by Shaikha Alkhaldi to her chapter'],
['p', 'UNTERM and Arabterm, a sample term list, medical examples (_allergic_, _allergen_, _contact eczema_), the research steps from Shaikha Alkhaldi’s terminology class notes (see Section 7), and the Damascus academy and the Coordination Bureau of Arabization in Rabat.'],

// ================= SAMIUALLAH =================
['h1', '6. Samiuallah Mohammad'],
['p', 'Material received: the typed version of the audiovisual translation notes (see Section 4), the first draft (Draft_one), the plan and recommendations (Latest updates and thoughts), the 180 course notes (typed and scanned), the Translation 1 notes, the notes on Farghal & Shunnaq, the Text Analysis Model, the text {{الترجمة: ماهيتها وكيفيتها}}, the framework document and the main document.'],
['h2', '6.1 The first draft: taken into the handbook'],
['p', 'The draft had 175 points. 8 were used as written, 148 were used after editing, and 19 were not used. Its 25 headings became the backbone of the handbook:'],
['table', ['Draft heading', 'Where it is now'], [
  ['Definitions and abbreviations', 'Key terms of each chapter; the Abbreviations list'],
  ['Objectives of the book', 'Preface'],
  ['Translation and the translator; qualities of a translator; commissioned and self-initiated translators', 'Chapter 1'],
  ['Tips on how to translate; titles', 'Chapters 2 and 22'],
  ['Arabic vs English', 'Chapter 4'],
  ['Form vs meaning', 'Chapter 5'],
  ['Types of meaning; sentence vs speaker meaning', 'Chapter 6'],
  ['Context; homonymy and polysemy', 'Chapter 7'],
  ['Collocation', 'Chapter 8'],
  ['Idioms', 'Chapter 9'],
  ['Equivalence', 'Chapter 10'],
  ['Literal and free translation', 'Chapter 11'],
  ['Metaphoric translation', 'Chapter 12'],
  ['Translation strategies (two headings)', 'Chapter 14, with part in Chapter 17'],
  ['Cultural approximation', 'Chapter 15'],
  ['Descriptive translation', 'Chapter 16'],
  ['Lexical creation', 'Chapter 17'],
  ['Analysing a text (with the KUNA example)', 'Chapter 18'],
  ['Post-editing', 'Chapter 22'],
  ['Commentary on translation', 'Chapter 25'],
  ['Terminology; machine translation; glossary; references (empty headings)', 'Written in full: Chapters 21 and 22, the Glossary and the References'],
], [55, 45]],
['h2', '6.2 The first draft: edited'],
['ul', [
  'Every section was rewritten as guided steps, and topics repeated in several places were merged.',
  '“Died” had the Arabic for “killed”: corrected.',
  '“Kick the bucket” was given with an insulting phrase ({{يموت كالحقير}}): it is now used to show that the idiom is informal and humorous, not insulting (Chapter 6).',
  'A line said form is more important than meaning: reversed, since meaning comes first.',
  '“Bush’s puppy”: the press said “poodle”.',
  '“Mark my words” was translated as a promise: corrected to {{تذكّر كلامي}}.',
  'The rule that Arabic always starts with the verb: corrected (Arabic often starts with the verb, but not always).',
  'The Arabic equivalent of “is”: corrected.',
  '_Sam ate the cake_ had been translated with “the apple” ({{التفاحة}}): corrected.',
  '_The Home Office_ had been translated as a minister ({{وزير}}): corrected to a ministry ({{وزارة}}).',
  'Some “idiom” examples were really collocations: moved to Chapter 8.',
  'Colloquial Egyptian expressions were replaced with formal ones, and examples that took a political or religious position were rewritten to stay neutral.',
]],
['h2', '6.3 The first draft: not taken, and why'],
['table', ['Not taken', 'Why'], [
  ['“Principles = Foundations”', 'Its meaning is unclear.'],
  ['“Arabic is compositional (derivational), English is compounding”', 'An oversimplification: both languages use derivation and compounding.'],
  ['“Translation also means to politicize (الدبلوماسية)”', 'The wrong word, and not a definition of translation.'],
  ['The communication model (sender, receiver, channel, noise)', 'Theory; the idea is kept in simple words.'],
  ['“Why is meaning complex? Because it is cognitive”', 'Theory a beginner cannot use.'],
  ['“Died = {{استشهد}}” as connotation', 'A religious and political word; replaced by {{تُوُفِّي}}.'],
  ['“Mule” as a synonym of “horse”', 'A mule is a different animal.'],
  ['_Kill_ vs _assassinated_', 'They differ in denotation, so they do not illustrate connotation.'],
  ['“Most of the time, literal translation fails”', 'The book shows many successful literal translations.'],
  ['“Kick the chair = انتحر”', 'Not an established English idiom.'],
  ['_She is a snake_ → {{إنها كالثعلب}}', 'Changes the image and contradicts the line before it.'],
  ['{{أول الغيث قطرة}} for “the tip of the iceberg”', 'It means that big things start small.'],
  ['The “74 fields” of the Jordanian academy', 'No source confirms the figure.'],
  ['“Death is the great leveller = كل نفس ذائقة الموت”', 'A Qur’anic verse should not be used as a translation equivalent.'],
  ['Colloquial register (“اتق الله يا شيخ”, “وحدوا الله”)', 'Not suitable for a general handbook.'],
  ['Zakat as “an Islamic taxation system”', 'Factually wrong: zakat is on wealth, not income.'],
  ['_Valentine’s Day_ = {{عيد الحب}} as a calque', 'It is not a loan translation.'],
  ['Invented words (tribocracy, dictatocracy, puppycracy, patriocracy)', 'Not established English words.'],
  ['“KUNA has biased views”', 'A handbook should not describe a named organisation this way.'],
  ['The Clinton impeachment examples', 'A political scandal involving a named person.'],
  ['Religious legal terms ({{الاستتابة}}, {{الخلوة الشرعية}}), Yin-Yang, _psychology_ vs _psychiatry_', 'They belong to other fields; left out for space.'],
  ['Some exercise items (_a readable book_, _a conceivable resolution_, _addled egg_, _Every Jack has his Jill_)', 'Left out for space; they could form an exercise set on the website.'],
], [45, 55]],
['h2', '6.4 The plan and recommendations'],
['p', 'The plan contained 38 requests once repeated ones are merged.'],
['table', ['Request', 'Status', 'Where it is now'], [
  ['Organise the material and remove repetition', 'Done', 'Whole book'],
  ['Add missing strategies and types of translation', 'Done', 'Chapters 1, 11, 14, 26'],
  ['A chapter on the seven procedures', 'Done', 'Chapter 13'],
  ['Define key concepts in every chapter', 'Done', 'Words to remember, every chapter'],
  ['A glossary of all terms', 'Partly done', 'Glossary of 113 terms; some terms used only in the text are not in it'],
  ['Chapters on machine translation, text analysis, commentary, dictionaries, terminology', 'Done', 'Chapters 22, 18, 25, 3, 21'],
  ['Tips and preparation at the beginning', 'Done', 'Chapter 2 and Start here'],
  ['The three questions: client, purpose, audience', 'Done', 'Chapter 2'],
  ['The main genres with examples; poetry examples', 'Done', 'Chapters 15 and 19'],
  ['An interlingual risk assessment matrix', 'Done', 'Chapter 24'],
  ['Common mistakes; an answer key with explanations', 'Done', 'Chapter 23; Try it in every chapter'],
  ['News texts as authentic material', 'Partly done', 'Chapters 2, 18 and 19 (headlines and a short report)'],
  ['Fairclough’s relational model', 'Partly done', 'Chapter 20, as three practical questions'],
  ['Collect examples from books, poetry, proverbs and idioms', 'Partly done', 'Chapters 9, 12, 15, 19'],
  ['A final practice section at three levels; checklists; a note on future editions and the Arabic version', 'Partly done', 'The three-level section, the four checklists and the note were removed (Section 8); one Translation quality checklist and one final task, Put it all together, remain'],
  ['Examples from “the book”', 'Not done', 'The book is not yet published'],
  ['Sentences from the Analysis and 386 texts', 'Not done', 'Not yet received'],
  ['Checklists based on the supervisor’s framework', 'Not done', 'The framework was not received'],
  ['References for the 180, 182 and other course materials', 'Partly done', 'Course materials cited as the Translation Team’s notes'],
], [44, 16, 40]],
['h2', '6.5 His course notes, the Text Analysis Model and {{الترجمة: ماهيتها وكيفيتها}}'],
['ul', [
  '**The 180 notes, the Translation 1 notes and the Farghal & Shunnaq notes** turned out to be the sources of the draft, so almost all of their content was already in the handbook. Added from them: _Ali often goes to bed early_ and _The students are in the laboratory_ (Chapter 4); _weak coffee_, _a rough sea_ and the collocations of {{يقطع}} (Chapter 8); _to be in the red_ and _Business is business_ ({{الشغل شغل}}) (Chapter 9); four examples of the seven procedures (Chapter 13); the citation of Farghal & Shunnaq in Chapters 4, 10, 12 and 15–17, in the 2011 edition the team used. The draft’s numbered exercises come from this book.',
  '**The Text Analysis Model** is used in full, in simpler words: the three steps (analysis, translation, commentary); the linguistic level, with its micro level (words, grammar, meaning, word forms, sound) and macro level (the text, other texts, point of view); and the external level (background, author, audience). It is in Chapter 18, Step 3, with its use in the commentary (Chapter 25) and as a quality check (Chapter 18, Step 5). Fairclough (2003), on which it is based, was added to the References. Not taken: blending, clippings, infixation, frame-modification, re-modelling, Al-ta’reed, monitoring, and intrinsic and extrinsic managing, which are too advanced.',
  '**{{الترجمة: ماهيتها وكيفيتها}}**: two idioms were taken (_He looks blue_, _I will go bananas_; Chapter 9). The rest was not quoted. The team’s plan asks that anything taken from this text be cited, but the pages received carry no author or publication details, so it cannot yet be listed in the References; in the handbook the two idioms are cited as the team’s course materials until those details are confirmed. Two of its examples needed correcting: “She is in the clouds” (the English idiom is “her head is in the clouds”) and {{مهّد الطريق}} for “break the ice”.',
  '**His framework instructions**: the principles-then-examples pattern, simple language for beginners, and citation rules are followed throughout. The outline is the contents page. The abbreviations are at the back rather than the front, and the answer key is inside each chapter rather than at the end (see Section 8).',
]],

// ================= SHAIKHAH =================
['h1', '7. Shaikha Alkhaldi'],
['p', 'This section lists the work done on the handbook by Shaikha Alkhaldi, with the place in the book where each piece can be found and the reason for it. It covers her own material, the structure of the book, the sections written for it, the examples, the checking, and the design.'],

['h2', '7.1 Her own material'],
['p', 'Her study notes (her course slides) were used in the chapters below. Each was rewritten in plain English, with an example before its technical name.'],
['table', ['Her notes', 'Where it is now'], [
  ['The three kinds of translation; the translator as a reader before being a writer', 'Chapter 1'],
  ['_be_, _do_ and _have_; the dual (for example {{المحكمان}}); the gender of _I_ and _you_; _She has her pills on time_', 'Chapter 4'],
  ['Lexical gaps ({{ثكلى}}), false equivalents, rare words', 'Chapter 6'],
  ['{{خط}}, a word with several meanings', 'Chapter 7'],
  ['One verb with several partners (_deliver a letter, a speech, a verdict_)', 'Chapter 8'],
  ['Fixed expressions; how to spot an idiom; five ways to translate one; three more idioms', 'Chapter 9'],
  ['The word-level strategies: a more general word, a more neutral word, paraphrase, a loan word plus explanation; Arabic words borrowed into English (_algebra_, _algorithm_)', 'Chapter 14'],
  ['Arabicisation ({{استراتيجية}}, {{تكنولوجيا}})', 'Chapter 17'],
  ['News headlines; the inverted pyramid; hard and soft news; technical and literary texts', 'Chapter 19'],
  ['Medical terms (_allergic_, _allergen_, _contact eczema_)', 'Chapter 21'],
  ['Translation memory, termbases, the development of machine translation, localisation', 'Chapter 22'],
  ['The Arabic dubbing of _The Simpsons_', 'Chapter 26'],
], [68, 32]],
['p', 'Her notes from the terminology course she took were used in Chapter 21, Steps 1 and 3 to 5: a term can be several words; read about a new field and ask a specialist; check a term’s parts against its context; confirm an equivalent in an original Arabic text; write a one-sentence definition; some concepts have two accepted names.'],

['h2', '7.2 Structure of the book'],
['ul', [
  '**The order of the book.** The 9 parts and 27 chapters run from easy to hard, so that each chapter uses only what the reader has already met. The dictionaries chapter was moved into Part 1 (Chapter 3), because a beginner needs a first tool before anything else.',
  '**One pattern for every chapter.** Each chapter opens with **Where we are**, teaches in numbered steps (the problem first, then the solution), gives questions to **Try it** with answers under **Check your answers**, and closes with **Remember**, **Words to remember** and **Next**, which names the following chapter. The pattern lets a beginner know what to expect and never lose the path.',
  '**The glossary.** The 113 terms come from the Words to remember boxes, in alphabetical order, each with its Arabic equivalent, definition and chapter. Where a term has two Arabic equivalents, they are joined with {{أو}} and the first is the preferred one.',
  '**The back matter.** The list of abbreviations, a Further reading list of five books, and the References (39 entries).',
  '**The contents page and running heads**, so that a reader always knows the part and the chapter.',
]],

['h2', '7.3 Sections written for the handbook'],
['p', 'The following were written where the team’s material did not cover a topic that the plan asked for. Each uses published sources, cited in brackets.'],
['table', ['Section', 'Where it is now', 'Main sources'], [
  ['Start here: translation in daily life, the House of Wisdom, the four steps of a translation, the way through the book', 'Front matter', '—'],
  ['Printed and digital dictionaries', 'Chapter 3', 'Johnson; Wehr; the dictionaries named in the chapter'],
  ['Communicative translation, the middle way between literal and free translation', 'Chapter 11, Step 4', 'Newmark (1988)'],
  ['The seven translation procedures', 'Chapter 13', 'Vinay & Darbelnet (1958/1995); Newmark (1988)'],
  ['Explicitation and implicitation; domestication and foreignisation; compensation', 'Chapter 14, Steps 3 to 5', 'Vinay & Darbelnet; Venuti (1995); Dickins et al. (2016)'],
  ['Words and points of view', 'Chapter 20', 'Fairclough (1992)'],
  ['Machine translation: what it does, its typical mistakes, correcting its output', 'Chapter 22', 'Kenny (2022)'],
  ['Revision and common mistakes', 'Chapter 23', 'Mossop (2014)'],
  ['Subtitle timing and spotting, SDH, a five-step method, rules for Arabic subtitles', 'Chapter 27', 'Díaz Cintas & Remael (2021)'],
  ['Your journey continues: daily habits, learning from real translations, where a translator can go next', 'End of the book', '—'],
], [46, 24, 30]],

['h2', '7.4 Examples and Arabic terms'],
['ul', [
  '**Opening example.** Start here opens with a real translation decision from a news report: _The government came under pressure to reconsider the decision._ → {{تعرّضت الحكومة لضغوط لإعادة النظر في القرار}}, against the word-for-word version. It shows a beginner in one look what a translator does: understand, decide and rebuild.',
  '**Every example was checked** against the team’s documents and her notes. Examples from the team were kept, with their errors corrected (Section 6.2). Examples that were weak were replaced, preferably with examples from the team’s files.',
  '**Examples added** where the team’s material had none: _the White House_ → {{البيت الأبيض}} (an established equivalent), _You can’t miss it_ → {{ستجده بسهولة}}, _Parking for residents only_ → {{ممنوع الوقوف لغير السكان}}, and the comparison in Chapter 11 of a too literal, a natural and a too free translation.',
  '**Three challenge questions** (Chapters 10, 14 and 15), each with a real sentence and two possible translations: the reader chooses the one that suits the audience and explains why.',
  '**Subtitling examples.** The subtitling examples are two famous, cited film lines, each explained: _The Godfather_ (condensing through Arabic syntax) and _Gone with the Wind_ (softening strong language).',
  '**Kuwaiti expressions.** Six expressions were chosen from the Kuwaiti expressions dictionary, following the proposal of Loulwah Bin Saeed (Section 4.1), and placed in Chapters 9, 15 and 27, with their English equivalents.',
  '**Arabic terms corrected.** Genre → {{نوع النص}}; Ideology → {{المنظومة الفكرية (الأيديولوجيا)}}; Loaded word → {{كلمة مشحونة دلالياً}}.',
  '**Rules framed as tendencies.** Statements such as “prefer a verbal sentence” and “use Modern Standard Arabic” now say that the text type, the audience, the purpose and the medium can change the choice (Chapters 4, 10, 20, 22 and 27); the subtitle conventions are marked as conventions, not rules.',
  '**Try it made clearer.** Every Try it opens with a line saying what it is for, its questions name the skill being practised, and its answers explain why.',
]],

['h2', '7.5 Guides and features for the reader'],
['ul', [
  '**The translator’s workflow** (end of Part 1): seven steps from reading to delivery, each linked to its chapter, with Do and Don’t boxes.',
  '**When in doubt** (before the closing section): what to do with an unknown word, with two possible translations, and with an answer from a machine.',
  '**Translation quality checklist** (end of Part 8): meaning, language, terms and names, details, and the final reading.',
  '**Put it all together** (after Chapter 27): one short press release taken through every step of the book, from the brief to a short commentary.',
  '**Ten “Did you know?” boxes** with short, true stories (the Rosetta Stone; the Universal Declaration of Human Rights; {{كتاب العين}}; Arabic numerals; the verb _run_; the journey of _coffee_; the Damascus academy; the 1954 machine-translation demonstration; the _Mars Climate Orbiter_; silent-film intertitles), so that the reader sees why translation matters. The intertitles come from the audiovisual translation notes.',
]],

['h2', '7.6 Checking and corrections'],
['ul', [
  'The whole book was reviewed in two full rounds, with 192 and then 102 corrections: definitions and concepts, Arabic grammar and terminology, examples that did not illustrate their point, cross-references, English, neutrality and citations.',
  'All 39 references and every direct quotation were checked twice against published information (authors, years, titles, publishers, DOIs and page numbers). Every citation in the text is matched to an entry in the References.',
  'After each round, every Arabic example was checked, so that none was lost or changed by mistake.',
  'Chapter numbers and cross-references were updated after the order of the book changed.',
  'Material tied to a date, an event or a product was reduced where possible, so that the book can be used year after year.',
]],

['h2', '7.7 Design and website'],
['ul', [
  'The two covers (Midnight and Light), designed with the club’s own logo.',
  'The page layout: light pages, a running head, roman numerals for the opening pages, and a size of 98 pages.',
  'The QR code on the back cover and on the last page of the book, which leads to the Translation Team’s website.',
  'The Translation Team’s website, which she created.',
]],

['h2', '7.8 Her proposals not taken, and why'],
['table', ['Not taken', 'Why'], [
  ['The parallel-texts step (“Intertextual Mapping Protocol”) and the ethics checklist (“Invisible Translator” audit)', 'They need texts and practice; they suit the website or a later edition. Parallel texts are mentioned in Your journey continues.'],
  ['“Dynamic Syntactic Restructuring” as a separate module', 'Partly covered by word order and verb-first sentences in Chapter 4.'],
  ['Quick-reference genre checklists for each text type', 'Replaced by one Translation quality checklist (end of Part 8) and the genre guidance in Chapter 19.'],
  ['The website’s Practice Arena and other features', 'They belong on the website, which carries what changes; the book carries what lasts.'],
], [45, 55]],

// ================= WHOLE BOOK =================
['h1', '8. Removed from the whole draft, and why'],
['table', ['Removed', 'Why'], [
  ['The practice section at three levels and its answer key', 'Too long for a handbook; each chapter keeps its Try it questions with answers.'],
  ['The four checklists at the end', 'They repeated the chapter summaries.'],
  ['The note on future editions and the Arabic version', 'A printed book cannot keep being updated; the website carries later material.'],
  ['Most scholars’ names in the running text', 'Easier reading; every idea keeps its citation in brackets.'],
  ['References to the courses and the lecturers', 'The handbook is meant to be used on its own.'],
  ['Part descriptions and about a third of the running text', 'Repetition and long explanations made the pages heavy.'],
  ['Most examples tied to a date or event', 'So that the book stays valid every year.'],
  ['Placeholders, unconfirmed reviewers’ names and mentions of the Guild Season', 'Not final or not confirmed.'],
  ['The acknowledgements and the Contributors list', 'Left out of this draft; contributors will be credited in the final version.'],
], [42, 58]],

['h1', '9. Still open for the team'],
['p', 'Because this is a draft, the following need the team’s decision:'],
['redul', [
  'The Contributors list for the final version: the framework agreed that all four names appear equally.',
  'Whether to name the academic supervisor, Abdullah Bezea, in the handbook.',
  'The club’s official name: the draft says “Guild Professional Club”; the team’s main document says “The Professional English Club: Guild”.',
  'Whether the material not yet received should go into this edition: Loulwah’s Principles of Translation notes, the Gamal article and AVT Theory; Masooma’s Translation Texts and stylistics summary; the three sample analyses.',
  'Who shared the Kuwaiti expressions dictionary, and its author, publisher and year, so that it can be cited in full.',
  'The author and publication details of the text {{الترجمة: ماهيتها وكيفيتها}}, so that the two idioms taken from it can be cited in full.',
  'The page size: B5 now; A5 was the size of the model book.',
  'Before printing: a full read by a native Arabic specialist; checking the ten Did you know? facts and the open reference points listed in the Final Report.',
]],
];
